REFRESHCOOKIE: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UaEVOVUpHTkVNMVFURTRNMEZCTWpkQ05UZzVNRFUxUlRVd1FVSkRNRU13UmtGRVFrRXpSZyJ9.eyJodHRwczovL2FwaS5vcGVuYWkuY29tL3Byb2ZpbGUiOnsiZW1haWwiOiJpZWU4MDIxMUBwcm90b25tYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS9hdXRoIjp7InBvaWQiOiJvcmctSjQ5Y1BReDhlbmZaYTFjSTFRSG5DTXVlIiwidXNlcl9pZCI6InVzZXItazJEdVRHZ1YxbnVjc3BPd0ZqWkE5c05mIn0sImlzcyI6Imh0dHBzOi8vYXV0aDAub3BlbmFpLmNvbS8iLCJzdWIiOiJhdXRoMHw2NGI5MDI5NDg0NzA1MTRmZTQ1NjQzOTciLCJhdWQiOlsiaHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MSIsImh0dHBzOi8vb3BlbmFpLm9wZW5haS5hdXRoMGFwcC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNzAxNDQ0NjI0LCJleHAiOjE3MDIzMDg2MjQsImF6cCI6IlRkSkljYmUxNldvVEh0Tjk1bnl5d2g1RTR5T282SXRHIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCBtb2RlbC5yZWFkIG1vZGVsLnJlcXVlc3Qgb3JnYW5pemF0aW9uLnJlYWQgb3JnYW5pemF0aW9uLndyaXRlIG9mZmxpbmVfYWNjZXNzIn0.KUo79SwnfhIFSIqt9564pckYqrgMDeBIL_BNSLoXjC4Vibdxg4jDNa6k-GHJ6KRHYY7LXZ1AY4kvGEaGmEfJ-sxl6WbWTWfC5W8YdKm9-7RiAE0W7l1sF_0-WlHkVniAskrunucUraR7lNAXPolPP14CK4_pAq0rL3G9Ae8DLydoV6rs7yQW-K1iAb50uyyERS2QhgVLqOj4rC87J5t1R1JtrGYoL6OUEHJ_PBEvbawfIIsyw8EQqKiV-OWI6CU5bH4kNfQIxf4ceqaOq3T4jpBECncDaY5Q8ZS2YBnN0YntCY7eB0imPOLEXmNC5-7SuTtRhOPf_jCdBHMe0Vboqw"
USERTOKENS: # 用户token,可配置多个
  - "123456"
  - "123456"

# PROXY: "http://127.0.0.1:31280"  # 代理地址
# OAUTH_URL: https://xxxxx.xxx.com/ouath
database:
  default:
    type: "sqlite" # 数据库类型
    name: "./config/cool.sqlite" # 数据库名称,对于sqlite来说就是数据库文件名
    extra: busy_timeout=5000 # 扩展参数 如 busy_timeout=5000&journal_mode=ALL
    createdAt: "create_time" # 创建时间字段名称
    updatedAt: "update_time" # 更新时间字段名称
    # debug: true # 开启调试模式,启用后将在控制台打印相关sql语句
